In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import io
import seaborn as sns
from scipy.stats import ttest_ind
from scipy.stats import f_oneway
import statsmodels.api as sm
from statsmodels.graphics.gofplots import qqplot
from statsmodels.formula.api import ols
from scipy.stats import kruskal
from scipy.stats import shapiro
from scipy.stats import levene
from scipy.stats import kstest

### Q1. Dosage and Gender</br>
A researcher is interested in determining the effects of different dosages of a dietary supplement on the performance of both males and females on a physical endurance test.</br>
The three different dosages of the medicine are low, medium, and high, and the genders are male and female.</br>

Conduct an appropriate hypothesis test to determine the interaction effects of the test at a 1% significance level.

In [16]:
data = """Dietary,Supplement_Dosage,Test_values
Female,Low,35.6
Female,Medium,49.4
Female,High,55.2
Male,Low,92.2
Male,Medium,45.4
Male,High,70.8
Female,Low,56.9
Female,Medium,87.0
Female,High,23.4
Male,Low,45.9
Male,Medium,34.2
Male,High,98.9"""
df = pd.read_csv(io.StringIO(data))

df.head()

  Dietary Supplement_Dosage  Test_values
0  Female               Low         35.6
1  Female            Medium         49.4
2  Female              High         55.2
3    Male               Low         92.2
4    Male            Medium         45.4

In [17]:
model = ols('Test_values ~ C(Supplement_Dosage)*C(Dietary)', data=df).fit()
anova_table = sm.stats.anova_lm(model, type=2)
print(f'There is no significant difference in average performance on the physical endurance test based on gender, supplement dosage, or their interaction.')
anova_table

There is no significant difference in average performance on the physical endurance test based on gender, supplement dosage, or their interaction.

,df,sum_sq,mean_sq,F,PR(>F)
C(Supplement_Dosage),2.0,130.811667,65.405833,0.132190,0.878657
C(Dietary),1.0,532.000833,532.000833,1.075214,0.339742
C(Supplement_Dosage):C(Dietary),2.0,2869.201667,1434.600833,2.899438,0.131502
Residual,6.0,2968.715000,494.785833,NaN,NaN

### Q2. Fertiliser and Watering Frequency <br/>
A researcher wants to investigate the effects of two different fertilizers (‘A’ & ‘B’) and three watering frequencies (‘Low’, ‘Medium’, ‘High’) on the growth of tomato plants.<br/>

Is there a significant interaction between the fertilizer type and watering frequency on plant growth?<br/>

Conduct an appropriate hypothesis test to determine only the interaction effects of this research at a 5% significance level.

In [18]:
data = """Fertilizer,Watering_Frequency,Plant_Height
A,Low,15.2
A,Medium,20.7
A,High,24.3
B,Low,18.4
B,Medium,23.1
B,High,26.5
A,Low,32.7
A,Medium,21.7
A,High,27.3
B,Low,38.4
B,Medium,33.1
B,High,36.5
A,Low,12.2
A,Medium,22.7
A,High,35.3
B,Low,28.4
B,Medium,22.1
B,High,24.5"""
df = pd.read_csv(io.StringIO(data))
df.head()

  Fertilizer Watering_Frequency  Plant_Height
0          A                Low          15.2
1          A             Medium          20.7
2          A               High          24.3
3          B                Low          18.4
4          B             Medium          23.1

In [19]:
model = ols('Plant_Height ~ C(Watering_Frequency)*C(Fertilizer)', data=df).fit()
anova_table = sm.stats.anova_lm(model, type=2)
print(f'There is not enough evidence to suggest that there is a significant interaction between the fertilizer type and watering frequency on plant growth')
anova_table

There is not enough evidence to suggest that there is a significant interaction between the fertilizer type and watering frequency on plant growth

,df,sum_sq,mean_sq,F,PR(>F)
C(Watering_Frequency),2.0,100.634444,50.317222,0.903226,0.431117
C(Fertilizer),1.0,84.067222,84.067222,1.509060,0.242831
C(Watering_Frequency):C(Fertilizer),2.0,50.034444,25.017222,0.449075,0.648519
Residual,12.0,668.500000,55.708333,NaN,NaN

### Q3. Education vs Test
The Committee head of a national entrance exam wants to analyze if there are any differences in learning outcomes between students with different educational backgrounds (high school or college) and teaching methods (traditional or interactive) on test scores.

Conduct an appropriate hypothesis test to determine the main effects & interaction effects of the test at a 5% significance level.

In [21]:
data = """Education,Teaching_Method,Test_Score
High School,Traditional,72
High School,Interactive,85
College,Traditional,70
College,Interactive,92
High School,Traditional,74
High School,Interactive,97
College,Traditional,76
College,Interactive,94
High School,Traditional,86
High School,Interactive,90
College,Traditional,69
College,Interactive,78
High School,Traditional,82
High School,Interactive,93
College,Traditional,98
College,Interactive,92"""
df = pd.read_csv(io.StringIO(data))
df.head()

     Education Teaching_Method  Test_Score
0  High School     Traditional          72
1  High School     Interactive          85
2      College     Traditional          70
3      College     Interactive          92
4  High School     Traditional          74

In [24]:
model = ols('Test_Score ~ C(Education)*C(Teaching_Method)',data=df).fit()
anova_table = sm.stats.anova_lm(model,type=2)
print(f'The teaching method significantly impacts student test scores, whereas educational background does not.')
print(f'There is no significant interaction between educational background and teaching method on student performance.')
anova_table

The teaching method significantly impacts student test scores, whereas educational background does not.
There is no significant interaction between educational background and teaching method on student performance.

                                   df  sum_sq     mean_sq         F    PR(>F)
C(Education)                      1.0    6.25    6.250000  0.081477  0.780172
C(Teaching_Method)                1.0  552.25  552.250000  7.199348  0.019920
C(Education):C(Teaching_Method)   1.0    4.00    4.000000  0.052146  0.823216
Residual                         12.0  920.50   76.708333       NaN       NaN

### Q4. Sales Strategy
A data analyst is comparing the sales amounts (in dollars) for two different marketing strategies (A and B). The sales data for 20 days under each strategy is collected.


sales_strategy_A = [156, 153, 157, 154, 156, 159, 152, 156, 157, 154, 153, 157, 157,152, 155, 154, 151, 157, 155, 151]<br/>
sales_strategy_B = [135, 147, 126, 136, 158, 139, 163, 141, 156, 142, 130, 129, 161, 158, 117, 151, 121, 135, 123, 153]<br/>

Perform an appropriate test to assess if there is a significant difference in the sales distributions between Strategy A and Strategy B. Use a significance level of 0.05.

In [26]:
H0 = 'Strategy A and B are no significant difference'
HA = 'Strategy A and B are significant different'

sales_strategy_A = [156, 153, 157, 154, 156, 159, 152, 156, 157, 154, 153, 157, 157,152, 155, 154, 151, 157, 155, 151]
sales_strategy_B = [135, 147, 126, 136, 158, 139, 163, 141, 156, 142, 130, 129, 161, 158, 117, 151, 121, 135, 123, 153]
alpha = 0.05

stat, p_value = kstest(sales_strategy_A,sales_strategy_B)
print(f'stat is: {stat}, p_value:{p_value:.8f}')

if p_value < alpha:
    print(f'Reject HO means: {HA}')
else:
    print(f'Fail to Reject HO means: {H0}')

stat is: 0.65, p_value:0.00027050
Reject HO means: Strategy A and B are significant different

### Q5. Mobile App Response
A researcher is investigating the distribution of response times (in seconds) for two different versions of a mobile app, i.e. the time taken for a mobile app to respond to a user action, measured in seconds.

The goal is to determine if the response time distributions significantly differ between the two versions.

Data for 20 users for each app version is collected.

In [30]:
H0 = 'Response times A and B are no significant difference'
HA = 'Response times A and B are significant different'

response_times_version_A = [1.2, 1.3, 1.1, 1.4, 1.2, 1.3, 1.0, 1.5, 1.2, 1.3, 1.2, 1.4, 1.1, 1.3, 1.2, 1.5, 1.3, 1.4, 1.2, 1.3]
response_times_version_B = [1.6, 1.2, 1.3, 1.4, 1.1, 1.3, 1.2, 1.5, 1.3, 1.4, 1.2, 1.3, 1.2, 1.4, 1.1, 1.3, 1.5, 1.2, 1.3, 1.4]
alpha = 0.05

stat, p_value = kstest(response_times_version_A,response_times_version_B)
print(f'stat is: {stat}, p_value:{p_value:.8f}')

if p_value < alpha:
    print(f'Reject HO means: {HA}')
else:
    print(f'Fail to Reject HO means: {H0}')

stat is: 0.1, p_value:0.99999239
Fail to Reject HO means: Response times A and B are no significant difference

### Q6. Delivery Method
An online shopping platform is testing two different delivery methods to improve the delivery times for their customers.
The data below represents the delivery times (in hours) for a sample of orders using Method A and Method B.

delivery_method_A = [2.5, 3.2, 2.8, 3.5, 3.0, 2.7, 2.9, 3.1, 2.6, 3.3]<br/>
delivery_method_B = [3.8, 3.2, 3.5, 3.1, 3.9, 3.0, 3.3, 3.6, 3.4, 3.7]<br/>

Using an appropriate test, determine if there is a significant difference in the delivery time distributions between Method A and Method B. Use a significance level of 0.05.

In [31]:
H0 = 'Delivery methods A and B are no significant difference'
HA = 'Delivery methods A and B are significant different'

delivery_method_A = [2.5, 3.2, 2.8, 3.5, 3.0, 2.7, 2.9, 3.1, 2.6, 3.3]
delivery_method_B = [3.8, 3.2, 3.5, 3.1, 3.9, 3.0, 3.3, 3.6, 3.4, 3.7]
alpha = 0.05

stat, p_value = kstest(delivery_method_A,delivery_method_B)
print(f'stat is: {stat}, p_value:{p_value:.8f}')

if p_value < alpha:
    print(f'Reject HO means: {HA}')
else:
    print(f'Fail to Reject HO means: {H0}')

stat is: 0.5, p_value:0.16782134
Fail to Reject HO means: Delivery methods A and B are no significant difference

### Q7. Banking app
A bank is launching two different approaches (A and B) to encourage customers to adopt its new mobile banking app. The bank randomly assigns a group of customers to each approach and monitors their adoption rates over a month.<br/>

Data:<br/>

Group A (Approach A): [38, 40, 42, 37, 39, 41, 36, 35, 43, 38] <br/> 
Group B (Approach B): [48, 45, 46, 43, 50, 44, 49, 47, 42, 46] <br/>

Note: Assume both Group A & Group B follow the normal distribution.<br/>
Objective:<br/>

Assess whether the new incentive program in Approach B leads to a statistically significant improvement in the average adoption rates compared to Approach A.

Choose a suitable statistical test.

In [37]:
H0 = 'Groups A and B are no significant improvement'
HA = 'Groups B are significant improvement over Group A'

groupA = [38, 40, 42, 37, 39, 41, 36, 35, 43, 38]  
groupB = [48, 45, 46, 43, 50, 44, 49, 47, 42, 46] 

alpha = 0.05

stat, p_value = ttest_ind(groupA,groupB,alternative='less')
print(f'stat is: {stat}, p_value:{p_value:.10f}')

if p_value < alpha:
    print(f'Reject HO means: {HA}')
else:
    print(f'Fail to Reject HO means: {H0}')

stat is: -6.125851335983492, p_value:0.0000043591
Reject HO means: Groups B are significant improvement over Group A