In [ ]:
%pip install statsmodels

In [14]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from scipy.stats import norm
from scipy.stats import power
from scipy.stats import ttest_1samp
import os

### One Sample T testt

In [36]:
# H0 : pop_mean = 100
# H1 : pop_mean > 100
pop_mean = 100
iq_scores = [110, 105, 98, 102, 99, 104, 115, 95]
t_stat, p_value = ttest_1samp(iq_scores, pop_mean)
print(f"T-statistic: {t_stat}, P-value: {p_value}")

alpha=0.01

if p_value < alpha:
    print("Reject the H0 - NULL hypothesis: The average IQ score is significantly different from 100.")
else:
    print("Fail to reject the H0 - NULL hypothesis: The average IQ score is not significantly different from 100.")

T-statistic: 1.5071573172061195, P-value: 0.1754994493585011
Fail to reject the H0 - NULL hypothesis: The average IQ score is not significantly different from 100.

Two Sample T test

In [21]:
script_dir = os.path.dirname(os.path.abspath('__file__'))
print(script_dir)
df_iq = pd.read_csv('D:\\learning\\ScalerDSML\\assets\\iq_two_schools.csv')
df_iq.head()

d:\learning\ScalerDSML\5_DAV3\Class5

     School   iq
0  school_1   91
1  school_1   95
2  school_1  110
3  school_1  112
4  school_1  115

In [23]:
df_iq.value_counts()

School    iq
school_1  91     3
school_2  115    3
school_1  109    3
          112    3
school_2  95     3
          91     2
school_1  110    2
          114    2
          94     2
          99     2
school_2  109    2
          117    2
school_1  82     1
          95     1
          92     1
          85     1
          84     1
school_2  90     1
school_1  115    1
          113    1
          105    1
          89     1
school_2  108    1
          99     1
          92     1
          112    1
          111    1
          114    1
          116    1
          128    1
          129    1
          130    1
          133    1
Name: count, dtype: int64

In [24]:
df_iq.groupby('School')['iq'].mean()

School
school_1    101.153846
school_2    109.416667
Name: iq, dtype: float64

### H0 u1 = u2
### HA u1 != u2

In [27]:
from scipy.stats import ttest_1samp ## This is used for 1 sample
from scipy.stats import ttest_ind ## This is used for 2 sample

In [29]:
iq_1 = df_iq[df_iq['School'] == 'school_1']['iq']
iq_2 = df_iq[df_iq['School'] == 'school_2']['iq']

t_stat, p_value = ttest_ind(iq_1, iq_2, alternative="two-sided")
print(f"T-statistic: {t_stat}, P-value: {p_value}")

alpha = 0.05 # 95% confidence
if p_value < alpha:
    print("Reject the H0 - NULL hypothesis")
else:
    print("Fail to reject the H0 - NULL hypothesis")

T-statistic: -2.4056474861512704, P-value: 0.02004552710936217
Reject the H0 - NULL hypothesis

### Paired T Test

In [31]:
from scipy.stats import ttest_rel

In [33]:
df_ps = pd.read_csv('D:\\learning\\ScalerDSML\\assets\\problem_solving.csv')
df_ps.shape

(137, 3)

In [34]:
df_ps.head()

   id  test_1  test_2
0   0      40      38
1   1      49      44
2   2      65      69
3   3      59      63
4   4      44      43

### H0: No Impact (marks remain same), Problem Solving has no effect
### HA: Some effect (marks are not same), Problem solving has an effect

### Two tail test (H0 != HA)

In [39]:
statistic, p_value = ttest_rel(df_ps['test_1'], df_ps['test_2'])
print(f"T-statistic: {statistic}, P-value: {p_value}")

alpha = 0.05
if p_value < alpha:
    print(f"{p_value} < {alpha}")
    print("Reject the H0 - NULL hypothesis")
else:
    print(f"{p_value} >= {alpha}")
    print("Fail to reject the H0 - NULL hypothesis")

T-statistic: -5.502886353508166, P-value: 1.7958403537923126e-07
1.7958403537923126e-07 < 0.05
Reject the H0 - NULL hypothesis

# H0: No effect
# HA: Problem solving improved the scores (u1 < u2)

In [41]:
statistic, p_value = ttest_rel(df_ps['test_1'], df_ps['test_2'], alternative='less')
print(f"T-statistic: {statistic}, P-value: {p_value}")

alpha = 0.05
if p_value < alpha:
    print(f"{p_value} < {alpha}")
    print("Reject the H0 - NULL hypothesis")
else:
    print(f"{p_value} >= {alpha}")
    print("Fail to reject the H0 - NULL hypothesis")

T-statistic: -5.502886353508166, P-value: 8.979201768961563e-08
8.979201768961563e-08 < 0.05
Reject the H0 - NULL hypothesis